name: nba_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  json_annotation: any



dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.0+4
  dio: ^3.0.8
  json_model: any
  build_runner: any
  json_serializable: any
  rxdart: ^0.22.2
  image_collage_widget: ^1.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/team_logos/Lakers.png
    - assets/team_logos/Kings.png
    - assets/team_logos/Celtics.png
    - assets/team_logos/Bulls.png
    - assets/team_logos/Wizards.png
    - assets/team_logos/Knicks.png
    - assets/team_logos/Cavaliers.png
    - assets/team_logos/Nuggets.png
    - assets/team_logos/Jazz.png
    - assets/team_logos/Bucks.png
    - assets/team_logos/76ers.png
    - assets/team_logos/Hornets.png
    - assets/team_logos/Trail Blazers.png
    - assets/team_logos/Raptors.png
    - assets/team_logos/Suns.png
    - assets/team_logos/Clippers.png
    - assets/team_logos/Spurs.png
    - assets/team_logos/Warriors.png
    - assets/team_logos/Pistons.png
    - assets/team_logos/Pelicans.png
    - assets/team_logos/Thunder.png
    - assets/team_logos/Grizzlies.png
    - assets/team_logos/Timberwolves.png
    - assets/team_logos/Mavericks.png
    - assets/team_logos/Nets.png
    - assets/team_logos/Heat.png
    - assets/team_logos/Hawks.png
    - assets/team_logos/Pacers.png
    - assets/team_logos/Rockets.png
    - assets/team_logos/Magic.png
    - assets/collages/CLE_DET.jpg
    - assets/collages/DET.png
    - assets/collages/DET.jpg
    - assets/collages/CLE.jpg
    - assets/collages/CLE.png
    - assets/collages/DET2.png
    - assets/collages/CLE2.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Alatsi
      fonts:
        - asset: assets/fonts/Alatsi-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
