name: nba_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  json_annotation: any
  permission_handler: ^8.2.5
  marquee: ^2.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.0-nullsafety.0
  http_parser: ^4.0.0-nullsafety
  dio: ^4.0.4
  json_model: any
  build_runner: any
  json_serializable: any
  rxdart: ^0.27.3
  intl: ^0.17.0
  shared_preferences: ^0.5.6+2


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/team_logos/Lakers.png
    - assets/team_logos/Kings.png
    - assets/team_logos/Celtics.png
    - assets/team_logos/Bulls.png
    - assets/team_logos/Wizards.png
    - assets/team_logos/Knicks.png
    - assets/team_logos/Cavaliers.png
    - assets/team_logos/Nuggets.png
    - assets/team_logos/Jazz.png
    - assets/team_logos/Bucks.png
    - assets/team_logos/76ers.png
    - assets/team_logos/Hornets.png
    - assets/team_logos/TrailBlazers.png
    - assets/team_logos/Raptors.png
    - assets/team_logos/Suns.png
    - assets/team_logos/Clippers.png
    - assets/team_logos/Spurs.png
    - assets/team_logos/Warriors.png
    - assets/team_logos/Pistons.png
    - assets/team_logos/Pelicans.png
    - assets/team_logos/Thunder.png
    - assets/team_logos/Grizzlies.png
    - assets/team_logos/Timberwolves.png
    - assets/team_logos/Mavericks.png
    - assets/team_logos/Nets.png
    - assets/team_logos/Heat.png
    - assets/team_logos/Hawks.png
    - assets/team_logos/Pacers.png
    - assets/team_logos/Rockets.png
    - assets/team_logos/Magic.png
    - assets/nba_images/bball.png
    - assets/nba_images/ball.png
    - assets/nba_images/gif.gif
    - assets/nba_images/gif2.gif
    - assets/nba_images/gif3.gif
    - assets/nba_images/gif4.gif

    - assets/collages/MILaway.jpg
    - assets/collages/CHAaway.jpg
    - assets/collages/OKCaway.jpg
    - assets/collages/LALaway.jpg
    - assets/collages/LACaway.jpg
    - assets/collages/MIAaway.jpg
    - assets/collages/ATLaway.jpg
    - assets/collages/ATLhome.jpg
    - assets/collages/DENaway.jpg
    - assets/collages/OKCaway.jpg
    - assets/collages/WASaway.jpg
    - assets/collages/TORaway.jpg
    - assets/collages/PHIaway.jpg
    - assets/collages/BOSaway.jpg
    - assets/collages/BKNaway.jpg
    - assets/collages/NYKaway.jpg
    - assets/collages/DETaway.jpg
    - assets/collages/ORLaway.jpg
    - assets/collages/CLEaway.jpg
    - assets/collages/CHIaway.jpg
    - assets/collages/HOUaway.jpg
    - assets/collages/SASaway.jpg
    - assets/collages/MEMaway.jpg
    - assets/collages/NOPaway.jpg
    - assets/collages/DALaway.jpg
    - assets/collages/GSWaway.jpg
    - assets/collages/SACaway.jpg
    - assets/collages/PHXaway.jpg
    - assets/collages/PORaway.jpg
    - assets/collages/UTAaway.jpg
    - assets/collages/MINaway.jpg
    - assets/collages/INDhome.jpg
    - assets/collages/LAChome.jpg
    - assets/collages/DENhome.jpg
    - assets/collages/CHIhome.jpg
    - assets/collages/GSWhome.jpg
    - assets/collages/MEMhome.jpg
    - assets/collages/SAShome.jpg
    - assets/collages/LALhome.jpg
    - assets/collages/UTAhome.jpg
    - assets/collages/INDhome.jpg
    - assets/collages/CLEhome.jpg
    - assets/collages/HOUhome.jpg
    - assets/collages/NOPhome.jpg
    - assets/collages/DALhome.jpg
    - assets/collages/NYKhome.jpg
    - assets/collages/BKNhome.jpg
    - assets/collages/BOShome.jpg
    - assets/collages/WAShome.jpg
    - assets/collages/CHAhome.jpg
    - assets/collages/ORLhome.jpg
    - assets/collages/PHIhome.jpg
    - assets/collages/TORhome.jpg
    - assets/collages/DEThome.jpg
    - assets/collages/OKChome.jpg
    - assets/collages/MILhome.jpg
    - assets/collages/PORhome.jpg
    - assets/collages/MINhome.jpg
    - assets/collages/PHXhome.jpg
    - assets/collages/SAChome.jpg
    - assets/collages/INDaway.jpg
    - assets/collages/MIAhome.jpg
    - assets/collages/details/NOPdet.jpg
    - assets/collages/details/LALdet.jpg




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Alatsi
      fonts:
        - asset: assets/fonts/Alatsi-Regular.ttf
    - family: Jomo
      fonts:
        - asset: assets/fonts/Jomolhari-Regular.ttf
    - family: Caladea
      fonts:
        - asset: assets/fonts/Caladea-Regular.ttf
    - family: Alata
      fonts:
        - asset: assets/fonts/alata.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
