class PlayerInfo {
  PlayerInfo({
    required this.name,
      required this.gameId,
      required this.teamId,
      required this.points,
      required this.pos,
      required this.min,
      required this.fgm,
      required this.fga,
      required this.fgp,
      required this.ftm,
      required this.fta,
      required this.ftp,
      required this.tpm,
      required this.tpa,
      required this.tpp,
      required this.offReb,
      required this.defReb,
      required this.totReb,
      required this.assists,
      required this.pFouls,
      required this.steals,
      required this.turnovers,
      required this.blocks,
      required this.plusMinus,
      required this.playerId});
  String name;
  String gameId;
  String teamId;
  int points;
  String pos;
  String min;
  String fgm;
  String fga;
  String fgp;
  String ftm;
  String fta;
  String ftp;
  String tpm;
  String tpa;
  String tpp;
  String offReb;
  String defReb;
  int totReb;
  int assists;
  String pFouls;
  String steals;
  String turnovers;
  String blocks;
  int plusMinus;
  String playerId;

}
